#define CONFIG_ARCH "cris"

#define CONFIG_ATM_FORE200E_DEBUG 0

#define CONFIG_ATM_FORE200E_TX_RETRY 16

#undef CONFIG_BASE_SMALL
#if defined(CONFIG_BASE_FULL)
  #define CONFIG_BASE_SMALL 0
#endif
#if !defined(CONFIG_BASE_FULL)
  #define CONFIG_BASE_SMALL 1
#endif

#define CONFIG_BFIN_RX_DESC_NUM 20

#define CONFIG_BFIN_TX_DESC_NUM 10

#define CONFIG_BLK_DEV_RAM_COUNT 16

#define CONFIG_BLK_DEV_RAM_SIZE 4096

#undef CONFIG_BOOTPARAM_HUNG_TASK_PANIC_VALUE
#if (defined(CONFIG_DETECT_HUNG_TASK) && !defined(CONFIG_BOOTPARAM_HUNG_TASK_PANIC))
  #define CONFIG_BOOTPARAM_HUNG_TASK_PANIC_VALUE 0
#endif
#if (defined(CONFIG_DETECT_HUNG_TASK) && defined(CONFIG_BOOTPARAM_HUNG_TASK_PANIC) && (!defined(CONFIG_DETECT_HUNG_TASK) || defined(CONFIG_BOOTPARAM_HUNG_TASK_PANIC)))
  #define CONFIG_BOOTPARAM_HUNG_TASK_PANIC_VALUE 1
#endif

#undef CONFIG_BOOTPARAM_SOFTLOCKUP_PANIC_VALUE
#if (defined(CONFIG_DETECT_SOFTLOCKUP) && !defined(CONFIG_BOOTPARAM_SOFTLOCKUP_PANIC))
  #define CONFIG_BOOTPARAM_SOFTLOCKUP_PANIC_VALUE 0
#endif
#if (defined(CONFIG_DETECT_SOFTLOCKUP) && defined(CONFIG_BOOTPARAM_SOFTLOCKUP_PANIC) && (!defined(CONFIG_DETECT_SOFTLOCKUP) || defined(CONFIG_BOOTPARAM_SOFTLOCKUP_PANIC)))
  #define CONFIG_BOOTPARAM_SOFTLOCKUP_PANIC_VALUE 1
#endif

#define CONFIG_CDROM_PKTCDVD_BUFFERS 8

#define CONFIG_DE2104X_DSL 0

#define CONFIG_DEBUG_KMEMLEAK_EARLY_LOG_SIZE 400

#define CONFIG_DEBUG_OBJECTS_ENABLE_DEFAULT 1

#undef CONFIG_DEFAULT_IOSCHED
#if (defined(CONFIG_BLOCK) && defined(CONFIG_DEFAULT_DEADLINE))
  #define CONFIG_DEFAULT_IOSCHED "deadline"
#endif
#if (defined(CONFIG_BLOCK) && defined(CONFIG_DEFAULT_CFQ) && (!defined(CONFIG_BLOCK) || !defined(CONFIG_DEFAULT_DEADLINE)))
  #define CONFIG_DEFAULT_IOSCHED "cfq"
#endif
#if (defined(CONFIG_BLOCK) && defined(CONFIG_DEFAULT_NOOP) && (!defined(CONFIG_BLOCK) || !defined(CONFIG_DEFAULT_CFQ)) && (!defined(CONFIG_BLOCK) || !defined(CONFIG_DEFAULT_DEADLINE)))
  #define CONFIG_DEFAULT_IOSCHED "noop"
#endif

#define CONFIG_DEFAULT_MMAP_MIN_ADDR 4096

#undef CONFIG_DEFAULT_SECURITY
#if defined(CONFIG_DEFAULT_SECURITY_SELINUX)
  #define CONFIG_DEFAULT_SECURITY "selinux"
#endif
#if (defined(CONFIG_DEFAULT_SECURITY_SMACK) && !defined(CONFIG_DEFAULT_SECURITY_SELINUX))
  #define CONFIG_DEFAULT_SECURITY "smack"
#endif
#if (!defined(CONFIG_DEFAULT_SECURITY_SELINUX) && !defined(CONFIG_DEFAULT_SECURITY_SMACK) && defined(CONFIG_DEFAULT_SECURITY_TOMOYO))
  #define CONFIG_DEFAULT_SECURITY "tomoyo"
#endif
#if (!defined(CONFIG_DEFAULT_SECURITY_SELINUX) && !defined(CONFIG_DEFAULT_SECURITY_SMACK) && !defined(CONFIG_DEFAULT_SECURITY_TOMOYO) && defined(CONFIG_DEFAULT_SECURITY_DAC))
  #define CONFIG_DEFAULT_SECURITY ""
#endif

#undef CONFIG_DEFAULT_TCP_CONG
#if (defined(CONFIG_NET) && defined(CONFIG_DEFAULT_WESTWOOD) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_VEGAS)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_BIC)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_HTCP)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_CUBIC)) && defined(CONFIG_INET))
  #define CONFIG_DEFAULT_TCP_CONG "westwood"
#endif
#if (defined(CONFIG_NET) && defined(CONFIG_DEFAULT_HTCP) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_BIC)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_CUBIC)) && defined(CONFIG_INET))
  #define CONFIG_DEFAULT_TCP_CONG "htcp"
#endif
#if (defined(CONFIG_NET) && defined(CONFIG_INET) && defined(CONFIG_DEFAULT_BIC))
  #define CONFIG_DEFAULT_TCP_CONG "bic"
#endif
#if ((defined(CONFIG_NET) && defined(CONFIG_INET) && defined(CONFIG_DEFAULT_CUBIC) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_BIC))) || (defined(CONFIG_NET) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_RENO)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_VEGAS)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_BIC)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_HTCP)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_WESTWOOD)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_CUBIC)) && defined(CONFIG_INET)))
  #define CONFIG_DEFAULT_TCP_CONG "cubic"
#endif
#if (defined(CONFIG_DEFAULT_RENO) && defined(CONFIG_NET) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_VEGAS)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_BIC)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_HTCP)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_WESTWOOD)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_CUBIC)) && defined(CONFIG_INET))
  #define CONFIG_DEFAULT_TCP_CONG "reno"
#endif
#if (defined(CONFIG_NET) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_BIC)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_HTCP)) && defined(CONFIG_DEFAULT_VEGAS) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_CUBIC)) && defined(CONFIG_INET))
  #define CONFIG_DEFAULT_TCP_CONG "vegas"
#endif

#define CONFIG_DEFCONFIG_LIST "/lib/modules/$UNAME_RELEASE/.config"

#define CONFIG_DLCI_MAX 8

#define CONFIG_DM9000_DEBUGLEVEL 4

#define CONFIG_ETRAX_CMDLINE "root=/dev/mtdblock3"

#define CONFIG_ETRAX_DDR2_CONFIG 0

#define CONFIG_ETRAX_DDR2_MRS 0

#define CONFIG_ETRAX_DDR2_TIMING 0

#undef CONFIG_ETRAX_DEF_GIO_PA_OE
#if ((defined(CONFIG_ETRAXFS) && defined(CONFIG_ETRAX_ARCH_V32)) || (defined(CONFIG_ETRAX_ARCH_V32) && !defined(CONFIG_CRIS_MACH_ARTPEC3)))
  #define CONFIG_ETRAX_DEF_GIO_PA_OE 1c
#endif
#if (defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_CRIS_MACH_ARTPEC3) && (!defined(CONFIG_ETRAXFS) || !defined(CONFIG_ETRAX_ARCH_V32)))
  #define CONFIG_ETRAX_DEF_GIO_PA_OE 00000000
#endif

#undef CONFIG_ETRAX_DEF_GIO_PA_OUT
#if ((defined(CONFIG_ETRAXFS) && defined(CONFIG_ETRAX_ARCH_V32)) || (defined(CONFIG_ETRAX_ARCH_V32) && !defined(CONFIG_CRIS_MACH_ARTPEC3)))
  #define CONFIG_ETRAX_DEF_GIO_PA_OUT 00
#endif
#if (defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_CRIS_MACH_ARTPEC3) && (!defined(CONFIG_ETRAXFS) || !defined(CONFIG_ETRAX_ARCH_V32)))
  #define CONFIG_ETRAX_DEF_GIO_PA_OUT 00000000
#endif

#undef CONFIG_ETRAX_DEF_GIO_PB_OE
#if ((defined(CONFIG_ETRAXFS) && defined(CONFIG_ETRAX_ARCH_V32)) || (defined(CONFIG_ETRAX_ARCH_V32) && !defined(CONFIG_CRIS_MACH_ARTPEC3)))
  #define CONFIG_ETRAX_DEF_GIO_PB_OE 00000
#endif
#if (defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_CRIS_MACH_ARTPEC3) && (!defined(CONFIG_ETRAXFS) || !defined(CONFIG_ETRAX_ARCH_V32)))
  #define CONFIG_ETRAX_DEF_GIO_PB_OE 000000000
#endif

#undef CONFIG_ETRAX_DEF_GIO_PB_OUT
#if ((defined(CONFIG_ETRAXFS) && defined(CONFIG_ETRAX_ARCH_V32)) || (defined(CONFIG_ETRAX_ARCH_V32) && !defined(CONFIG_CRIS_MACH_ARTPEC3)))
  #define CONFIG_ETRAX_DEF_GIO_PB_OUT 00000
#endif
#if (defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_CRIS_MACH_ARTPEC3) && (!defined(CONFIG_ETRAXFS) || !defined(CONFIG_ETRAX_ARCH_V32)))
  #define CONFIG_ETRAX_DEF_GIO_PB_OUT 000000000
#endif

#define CONFIG_ETRAX_DEF_GIO_PC_OE 00000

#define CONFIG_ETRAX_DEF_GIO_PC_OUT 00000

#define CONFIG_ETRAX_DEF_GIO_PD_OE 00000

#define CONFIG_ETRAX_DEF_GIO_PD_OUT 00000

#define CONFIG_ETRAX_DEF_GIO_PE_OE 00000

#define CONFIG_ETRAX_DEF_GIO_PE_OUT 00000

#define CONFIG_ETRAX_DEF_GIO_PV_OE 0000

#define CONFIG_ETRAX_DEF_GIO_PV_OUT 0000

#define CONFIG_ETRAX_DEF_R_BUS_CONFIG 104

#define CONFIG_ETRAX_DEF_R_DRAM_CONFIG 1a200040

#define CONFIG_ETRAX_DEF_R_DRAM_TIMING 5611

#define CONFIG_ETRAX_DEF_R_PORT_PA_DATA 00

#define CONFIG_ETRAX_DEF_R_PORT_PA_DIR 1c

#define CONFIG_ETRAX_DEF_R_PORT_PB_CONFIG 00

#define CONFIG_ETRAX_DEF_R_PORT_PB_DATA ff

#define CONFIG_ETRAX_DEF_R_PORT_PB_DIR 00

#define CONFIG_ETRAX_DEF_R_SDRAM_CONFIG d2fa7878

#define CONFIG_ETRAX_DEF_R_SDRAM_TIMING 80004801

#define CONFIG_ETRAX_DEF_R_WAITSTATES 95a6

#define CONFIG_ETRAX_DRAM_SIZE 8

#undef CONFIG_ETRAX_DRAM_VIRTUAL_BASE
#if ((defined(CONFIG_ETRAX_ARCH_V10) && !defined(CONFIG_ETRAX100LX)) || (defined(CONFIG_ETRAXFS) && defined(CONFIG_ETRAX_ARCH_V32) && !defined(CONFIG_ETRAX_ARCH_V10)) || (defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_CRIS_MACH_ARTPEC3) && !defined(CONFIG_ETRAX_ARCH_V10) && (!defined(CONFIG_ETRAXFS) || !defined(CONFIG_ETRAX_ARCH_V32))) || (!defined(CONFIG_ETRAX_ARCH_V10) && (!defined(CONFIG_ETRAXFS) || !defined(CONFIG_ETRAX_ARCH_V32)) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_CRIS_MACH_ARTPEC3)) && defined(CONFIG_ETRAX_ARCH_V32)))
  #define CONFIG_ETRAX_DRAM_VIRTUAL_BASE c0000000
#endif
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX100LX) && (!defined(CONFIG_ETRAX_ARCH_V10) || defined(CONFIG_ETRAX100LX)))
  #define CONFIG_ETRAX_DRAM_VIRTUAL_BASE 60000000
#endif

#define CONFIG_ETRAX_DS1302_RSTBIT 2

#define CONFIG_ETRAX_DS1302_SCLBIT 1

#define CONFIG_ETRAX_DS1302_SDABIT 0

#define CONFIG_ETRAX_DS1302_TRICKLE_CHARGE 0

#define CONFIG_ETRAX_FLASH1_SIZE 0

#define CONFIG_ETRAX_FLASH_BUSWIDTH 2

#define CONFIG_ETRAX_I2C_CLK_PORT 1

#define CONFIG_ETRAX_I2C_DATA_PORT 0

#define CONFIG_ETRAX_LED10Y 2

#define CONFIG_ETRAX_LED11Y 2

#define CONFIG_ETRAX_LED12R 2

#define CONFIG_ETRAX_LED1G 2

#define CONFIG_ETRAX_LED1R 3

#define CONFIG_ETRAX_LED2G 4

#define CONFIG_ETRAX_LED2R 5

#define CONFIG_ETRAX_LED3G 2

#define CONFIG_ETRAX_LED3R 2

#define CONFIG_ETRAX_LED4G 2

#define CONFIG_ETRAX_LED4R 2

#define CONFIG_ETRAX_LED5G 2

#define CONFIG_ETRAX_LED5R 2

#define CONFIG_ETRAX_LED6G 2

#define CONFIG_ETRAX_LED6R 2

#define CONFIG_ETRAX_LED7G 2

#define CONFIG_ETRAX_LED7R 2

#define CONFIG_ETRAX_LED8Y 2

#define CONFIG_ETRAX_LED9Y 2

#define CONFIG_ETRAX_LED_G_NET0 "PA3"

#define CONFIG_ETRAX_LED_G_NET1 ""

#define CONFIG_ETRAX_LED_R_NET0 "PA4"

#define CONFIG_ETRAX_LED_R_NET1 ""

#define CONFIG_ETRAX_MEM_GRP1_CONFIG 4044a

#define CONFIG_ETRAX_MEM_GRP2_CONFIG 0

#define CONFIG_ETRAX_MEM_GRP3_CONFIG 0

#define CONFIG_ETRAX_MEM_GRP4_CONFIG 0

#define CONFIG_ETRAX_NANDFLASH_BUSWIDTH 1

#define CONFIG_ETRAX_PA_BUTTON_BITMASK 02

#undef CONFIG_ETRAX_PA_CHANGEABLE_BITS
#if ((defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_GPIO)) || (defined(CONFIG_ETRAX_ARCH_V10) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || defined(CONFIG_ETRAXFS)) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || !defined(CONFIG_ETRAXFS)) && defined(CONFIG_ETRAX_GPIO)))
  #define CONFIG_ETRAX_PA_CHANGEABLE_BITS FF
#endif
#if (defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_ETRAX_GPIO) && defined(CONFIG_ETRAXFS) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_GPIO)))
  #define CONFIG_ETRAX_PA_CHANGEABLE_BITS 0x00
#endif
#if (((!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_GPIO)) && !defined(CONFIG_ETRAXFS) && defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_ETRAX_GPIO) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || !defined(CONFIG_ETRAXFS))) || ((!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_GPIO)) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || defined(CONFIG_ETRAXFS)) && !defined(CONFIG_ETRAXFS) && defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_ETRAX_GPIO) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || !defined(CONFIG_ETRAXFS))))
  #define CONFIG_ETRAX_PA_CHANGEABLE_BITS 0x00000000
#endif

#undef CONFIG_ETRAX_PA_CHANGEABLE_DIR
#if ((defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_GPIO)) || (defined(CONFIG_ETRAX_ARCH_V10) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || defined(CONFIG_ETRAXFS)) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || !defined(CONFIG_ETRAXFS)) && defined(CONFIG_ETRAX_GPIO)))
  #define CONFIG_ETRAX_PA_CHANGEABLE_DIR 00
#endif
#if (defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_ETRAX_GPIO) && defined(CONFIG_ETRAXFS) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_GPIO)))
  #define CONFIG_ETRAX_PA_CHANGEABLE_DIR 0x00
#endif
#if (((!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_GPIO)) && !defined(CONFIG_ETRAXFS) && defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_ETRAX_GPIO) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || !defined(CONFIG_ETRAXFS))) || ((!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_GPIO)) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || defined(CONFIG_ETRAXFS)) && !defined(CONFIG_ETRAXFS) && defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_ETRAX_GPIO) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || !defined(CONFIG_ETRAXFS))))
  #define CONFIG_ETRAX_PA_CHANGEABLE_DIR 0x00000000
#endif

#undef CONFIG_ETRAX_PB_CHANGEABLE_BITS
#if ((defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_GPIO)) || (defined(CONFIG_ETRAX_ARCH_V10) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || defined(CONFIG_ETRAXFS)) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || !defined(CONFIG_ETRAXFS)) && defined(CONFIG_ETRAX_GPIO)))
  #define CONFIG_ETRAX_PB_CHANGEABLE_BITS FF
#endif
#if (defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_ETRAX_GPIO) && defined(CONFIG_ETRAXFS) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_GPIO)))
  #define CONFIG_ETRAX_PB_CHANGEABLE_BITS 0x00000
#endif
#if (((!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_GPIO)) && !defined(CONFIG_ETRAXFS) && defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_ETRAX_GPIO) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || !defined(CONFIG_ETRAXFS))) || ((!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_GPIO)) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || defined(CONFIG_ETRAXFS)) && !defined(CONFIG_ETRAXFS) && defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_ETRAX_GPIO) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || !defined(CONFIG_ETRAXFS))))
  #define CONFIG_ETRAX_PB_CHANGEABLE_BITS 0x00000000
#endif

#undef CONFIG_ETRAX_PB_CHANGEABLE_DIR
#if ((defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_GPIO)) || (defined(CONFIG_ETRAX_ARCH_V10) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || defined(CONFIG_ETRAXFS)) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || !defined(CONFIG_ETRAXFS)) && defined(CONFIG_ETRAX_GPIO)))
  #define CONFIG_ETRAX_PB_CHANGEABLE_DIR 00
#endif
#if (defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_ETRAX_GPIO) && defined(CONFIG_ETRAXFS) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_GPIO)))
  #define CONFIG_ETRAX_PB_CHANGEABLE_DIR 0x00000
#endif
#if (((!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_GPIO)) && !defined(CONFIG_ETRAXFS) && defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_ETRAX_GPIO) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || !defined(CONFIG_ETRAXFS))) || ((!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_GPIO)) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || defined(CONFIG_ETRAXFS)) && !defined(CONFIG_ETRAXFS) && defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_ETRAX_GPIO) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || !defined(CONFIG_ETRAXFS))))
  #define CONFIG_ETRAX_PB_CHANGEABLE_DIR 0x00000000
#endif

#define CONFIG_ETRAX_PC_CHANGEABLE_BITS 0x00000

#undef CONFIG_ETRAX_PC_CHANGEABLE_DIR
#if (defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_ETRAX_GPIO) && defined(CONFIG_ETRAXFS))
  #define CONFIG_ETRAX_PC_CHANGEABLE_DIR 0x00000
#endif
#if (defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_ETRAX_GPIO) && !defined(CONFIG_ETRAXFS) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_ETRAX_GPIO) || !defined(CONFIG_ETRAXFS)))
  #define CONFIG_ETRAX_PC_CHANGEABLE_DIR 0x00000000
#endif

#define CONFIG_ETRAX_PD_CHANGEABLE_BITS 0x00000

#define CONFIG_ETRAX_PD_CHANGEABLE_DIR 0x00000

#define CONFIG_ETRAX_PE_CHANGEABLE_BITS 0x00000

#define CONFIG_ETRAX_PE_CHANGEABLE_DIR 0x00000

#define CONFIG_ETRAX_PIO_CE0_CFG 0

#define CONFIG_ETRAX_PIO_CE1_CFG 0

#define CONFIG_ETRAX_PIO_CE2_CFG 0

#define CONFIG_ETRAX_POWERBUTTON_BIT 25

#define CONFIG_ETRAX_PTABLE_SECTOR 65536

#define CONFIG_ETRAX_PV_CHANGEABLE_BITS 0x0000

#define CONFIG_ETRAX_PV_CHANGEABLE_DIR 0x0000

#define CONFIG_ETRAX_RS485_ON_PA_BIT 3

#define CONFIG_ETRAX_SDRAM_COMMAND 0

#define CONFIG_ETRAX_SDRAM_GRP0_CONFIG 336

#define CONFIG_ETRAX_SDRAM_GRP1_CONFIG 0

#define CONFIG_ETRAX_SDRAM_TIMING 104a

//WARNING: no defaults for CONFIG_ETRAX_SER0_CD_BIT
#define CONFIG_ETRAX_SER0_CD_BIT ""

#undef CONFIG_ETRAX_SER0_CD_ON_PA_BIT
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT0) && !defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PA) && !defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER0_CD_ON_PA_BIT -1
#endif
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT0) && (defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_SERIAL_PORT0) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER0_CD_ON_PA_BIT 7
#endif

#undef CONFIG_ETRAX_SER0_CD_ON_PB_BIT
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT0) && !defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PB) && !defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER0_CD_ON_PB_BIT -1
#endif
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT0) && (defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_SERIAL_PORT0) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER0_CD_ON_PB_BIT 7
#endif

//WARNING: no defaults for CONFIG_ETRAX_SER0_DSR_BIT
#define CONFIG_ETRAX_SER0_DSR_BIT ""

#undef CONFIG_ETRAX_SER0_DSR_ON_PA_BIT
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT0) && !defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PA) && !defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER0_DSR_ON_PA_BIT -1
#endif
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT0) && (defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_SERIAL_PORT0) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER0_DSR_ON_PA_BIT 6
#endif

#undef CONFIG_ETRAX_SER0_DSR_ON_PB_BIT
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT0) && !defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PB) && !defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER0_DSR_ON_PB_BIT -1
#endif
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT0) && (defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_SERIAL_PORT0) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER0_DSR_ON_PB_BIT 6
#endif

//WARNING: no defaults for CONFIG_ETRAX_SER0_DTR_BIT
#define CONFIG_ETRAX_SER0_DTR_BIT ""

#undef CONFIG_ETRAX_SER0_DTR_ON_PA_BIT
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT0) && !defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PA) && !defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER0_DTR_ON_PA_BIT -1
#endif
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT0) && (defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_SERIAL_PORT0) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER0_DTR_ON_PA_BIT 4
#endif

#undef CONFIG_ETRAX_SER0_DTR_ON_PB_BIT
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT0) && !defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PB) && !defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER0_DTR_ON_PB_BIT -1
#endif
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT0) && (defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_SERIAL_PORT0) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER0_DTR_ON_PB_BIT 4
#endif

//WARNING: no defaults for CONFIG_ETRAX_SER0_RI_BIT
#define CONFIG_ETRAX_SER0_RI_BIT ""

#undef CONFIG_ETRAX_SER0_RI_ON_PA_BIT
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT0) && !defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PA) && !defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER0_RI_ON_PA_BIT -1
#endif
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT0) && (defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_SERIAL_PORT0) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER0_RI_ON_PA_BIT 5
#endif

#undef CONFIG_ETRAX_SER0_RI_ON_PB_BIT
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT0) && !defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PB) && !defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER0_RI_ON_PB_BIT -1
#endif
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT0) && (defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_SERIAL_PORT0) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER0_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER0_RI_ON_PB_BIT 5
#endif

//WARNING: no defaults for CONFIG_ETRAX_SER1_CD_BIT
#define CONFIG_ETRAX_SER1_CD_BIT ""

#undef CONFIG_ETRAX_SER1_CD_ON_PA_BIT
#if (defined(CONFIG_ETRAX_SERIAL_PORT1) && defined(CONFIG_ETRAX_ARCH_V10) && !defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PA) && !defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER1_CD_ON_PA_BIT -1
#endif
#if (defined(CONFIG_ETRAX_SERIAL_PORT1) && defined(CONFIG_ETRAX_ARCH_V10) && (defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_SERIAL_PORT1) || !defined(CONFIG_ETRAX_ARCH_V10) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER1_CD_ON_PA_BIT 7
#endif

#undef CONFIG_ETRAX_SER1_CD_ON_PB_BIT
#if (defined(CONFIG_ETRAX_SERIAL_PORT1) && defined(CONFIG_ETRAX_ARCH_V10) && !defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PB) && !defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER1_CD_ON_PB_BIT -1
#endif
#if (defined(CONFIG_ETRAX_SERIAL_PORT1) && defined(CONFIG_ETRAX_ARCH_V10) && (defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_SERIAL_PORT1) || !defined(CONFIG_ETRAX_ARCH_V10) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER1_CD_ON_PB_BIT 7
#endif

//WARNING: no defaults for CONFIG_ETRAX_SER1_DSR_BIT
#define CONFIG_ETRAX_SER1_DSR_BIT ""

#undef CONFIG_ETRAX_SER1_DSR_ON_PA_BIT
#if (defined(CONFIG_ETRAX_SERIAL_PORT1) && defined(CONFIG_ETRAX_ARCH_V10) && !defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PA) && !defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER1_DSR_ON_PA_BIT -1
#endif
#if (defined(CONFIG_ETRAX_SERIAL_PORT1) && defined(CONFIG_ETRAX_ARCH_V10) && (defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_SERIAL_PORT1) || !defined(CONFIG_ETRAX_ARCH_V10) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER1_DSR_ON_PA_BIT 6
#endif

#undef CONFIG_ETRAX_SER1_DSR_ON_PB_BIT
#if (defined(CONFIG_ETRAX_SERIAL_PORT1) && defined(CONFIG_ETRAX_ARCH_V10) && !defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PB) && !defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER1_DSR_ON_PB_BIT -1
#endif
#if (defined(CONFIG_ETRAX_SERIAL_PORT1) && defined(CONFIG_ETRAX_ARCH_V10) && (defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_SERIAL_PORT1) || !defined(CONFIG_ETRAX_ARCH_V10) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER1_DSR_ON_PB_BIT 6
#endif

//WARNING: no defaults for CONFIG_ETRAX_SER1_DTR_BIT
#define CONFIG_ETRAX_SER1_DTR_BIT ""

#undef CONFIG_ETRAX_SER1_DTR_ON_PA_BIT
#if (defined(CONFIG_ETRAX_SERIAL_PORT1) && defined(CONFIG_ETRAX_ARCH_V10) && !defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PA) && !defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER1_DTR_ON_PA_BIT -1
#endif
#if (defined(CONFIG_ETRAX_SERIAL_PORT1) && defined(CONFIG_ETRAX_ARCH_V10) && (defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_SERIAL_PORT1) || !defined(CONFIG_ETRAX_ARCH_V10) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER1_DTR_ON_PA_BIT 4
#endif

#undef CONFIG_ETRAX_SER1_DTR_ON_PB_BIT
#if (defined(CONFIG_ETRAX_SERIAL_PORT1) && defined(CONFIG_ETRAX_ARCH_V10) && !defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PB) && !defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER1_DTR_ON_PB_BIT -1
#endif
#if (defined(CONFIG_ETRAX_SERIAL_PORT1) && defined(CONFIG_ETRAX_ARCH_V10) && (defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_SERIAL_PORT1) || !defined(CONFIG_ETRAX_ARCH_V10) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER1_DTR_ON_PB_BIT 4
#endif

//WARNING: no defaults for CONFIG_ETRAX_SER1_RI_BIT
#define CONFIG_ETRAX_SER1_RI_BIT ""

#undef CONFIG_ETRAX_SER1_RI_ON_PA_BIT
#if (defined(CONFIG_ETRAX_SERIAL_PORT1) && defined(CONFIG_ETRAX_ARCH_V10) && !defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PA) && !defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER1_RI_ON_PA_BIT -1
#endif
#if (defined(CONFIG_ETRAX_SERIAL_PORT1) && defined(CONFIG_ETRAX_ARCH_V10) && (defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_SERIAL_PORT1) || !defined(CONFIG_ETRAX_ARCH_V10) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER1_RI_ON_PA_BIT 5
#endif

#undef CONFIG_ETRAX_SER1_RI_ON_PB_BIT
#if (defined(CONFIG_ETRAX_SERIAL_PORT1) && defined(CONFIG_ETRAX_ARCH_V10) && !defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PB) && !defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER1_RI_ON_PB_BIT -1
#endif
#if (defined(CONFIG_ETRAX_SERIAL_PORT1) && defined(CONFIG_ETRAX_ARCH_V10) && (defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_SERIAL_PORT1) || !defined(CONFIG_ETRAX_ARCH_V10) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER1_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER1_RI_ON_PB_BIT 5
#endif

//WARNING: no defaults for CONFIG_ETRAX_SER2_CD_BIT
#define CONFIG_ETRAX_SER2_CD_BIT ""

#undef CONFIG_ETRAX_SER2_CD_ON_PA_BIT
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT2) && !defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PA) && !defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER2_CD_ON_PA_BIT -1
#endif
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT2) && (defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_SERIAL_PORT2) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER2_CD_ON_PA_BIT 7
#endif

#undef CONFIG_ETRAX_SER2_CD_ON_PB_BIT
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT2) && !defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PB) && !defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER2_CD_ON_PB_BIT -1
#endif
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT2) && (defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_SERIAL_PORT2) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER2_CD_ON_PB_BIT 7
#endif

//WARNING: no defaults for CONFIG_ETRAX_SER2_DSR_BIT
#define CONFIG_ETRAX_SER2_DSR_BIT ""

#undef CONFIG_ETRAX_SER2_DSR_ON_PA_BIT
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT2) && !defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PA) && !defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER2_DSR_ON_PA_BIT -1
#endif
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT2) && (defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_SERIAL_PORT2) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER2_DSR_ON_PA_BIT 6
#endif

#undef CONFIG_ETRAX_SER2_DSR_ON_PB_BIT
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT2) && !defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PB) && !defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER2_DSR_ON_PB_BIT -1
#endif
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT2) && (defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_SERIAL_PORT2) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER2_DSR_ON_PB_BIT 6
#endif

//WARNING: no defaults for CONFIG_ETRAX_SER2_DTR_BIT
#define CONFIG_ETRAX_SER2_DTR_BIT ""

#undef CONFIG_ETRAX_SER2_DTR_ON_PA_BIT
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT2) && !defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PA) && !defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER2_DTR_ON_PA_BIT -1
#endif
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT2) && (defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_SERIAL_PORT2) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER2_DTR_ON_PA_BIT 4
#endif

#undef CONFIG_ETRAX_SER2_DTR_ON_PB_BIT
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT2) && !defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PB) && !defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER2_DTR_ON_PB_BIT -1
#endif
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT2) && (defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_SERIAL_PORT2) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER2_DTR_ON_PB_BIT 4
#endif

//WARNING: no defaults for CONFIG_ETRAX_SER2_RI_BIT
#define CONFIG_ETRAX_SER2_RI_BIT ""

#undef CONFIG_ETRAX_SER2_RI_ON_PA_BIT
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT2) && !defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PA) && !defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER2_RI_ON_PA_BIT -1
#endif
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT2) && (defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_SERIAL_PORT2) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PA) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER2_RI_ON_PA_BIT 5
#endif

#undef CONFIG_ETRAX_SER2_RI_ON_PB_BIT
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT2) && !defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PB) && !defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED))
  #define CONFIG_ETRAX_SER2_RI_ON_PB_BIT -1
#endif
#if (defined(CONFIG_ETRAX_ARCH_V10) && defined(CONFIG_ETRAX_SERIAL_PORT2) && (defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED)) && (!defined(CONFIG_ETRAX_ARCH_V10) || !defined(CONFIG_ETRAX_SERIAL_PORT2) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_ON_PB) || defined(CONFIG_ETRAX_SER2_DTR_RI_DSR_CD_MIXED)))
  #define CONFIG_ETRAX_SER2_RI_ON_PB_BIT 5
#endif

//WARNING: no defaults for CONFIG_ETRAX_SER3_CD_BIT
#define CONFIG_ETRAX_SER3_CD_BIT ""

#define CONFIG_ETRAX_SER3_CD_ON_PA_BIT -1

#define CONFIG_ETRAX_SER3_CD_ON_PB_BIT -1

//WARNING: no defaults for CONFIG_ETRAX_SER3_DSR_BIT
#define CONFIG_ETRAX_SER3_DSR_BIT ""

#define CONFIG_ETRAX_SER3_DSR_ON_PA_BIT -1

#define CONFIG_ETRAX_SER3_DSR_ON_PB_BIT -1

//WARNING: no defaults for CONFIG_ETRAX_SER3_DTR_BIT
#define CONFIG_ETRAX_SER3_DTR_BIT ""

#define CONFIG_ETRAX_SER3_DTR_ON_PA_BIT -1

#define CONFIG_ETRAX_SER3_DTR_ON_PB_BIT -1

//WARNING: no defaults for CONFIG_ETRAX_SER3_RI_BIT
#define CONFIG_ETRAX_SER3_RI_BIT ""

#define CONFIG_ETRAX_SER3_RI_ON_PA_BIT -1

#define CONFIG_ETRAX_SER3_RI_ON_PB_BIT -1

//WARNING: no defaults for CONFIG_ETRAX_SER4_DSR_BIT
#define CONFIG_ETRAX_SER4_DSR_BIT ""

//WARNING: no defaults for CONFIG_ETRAX_SER4_DTR_BIT
#define CONFIG_ETRAX_SER4_DTR_BIT ""

//WARNING: no defaults for CONFIG_ETRAX_SER4_RI_BIT
#define CONFIG_ETRAX_SER4_RI_BIT ""

#undef CONFIG_ETRAX_SERIAL_PORTS
#if ((defined(CONFIG_ETRAXFS) && defined(CONFIG_ETRAX_ARCH_V32)) || (defined(CONFIG_ETRAXFS) && defined(CONFIG_ETRAX_ARCH_V32) && (!defined(CONFIG_ETRAX_ARCH_V32) || !defined(CONFIG_CRIS_MACH_ARTPEC3))))
  #define CONFIG_ETRAX_SERIAL_PORTS 4
#endif
#if (defined(CONFIG_ETRAX_ARCH_V32) && defined(CONFIG_CRIS_MACH_ARTPEC3) && (!defined(CONFIG_ETRAXFS) || !defined(CONFIG_ETRAX_ARCH_V32)))
  #define CONFIG_ETRAX_SERIAL_PORTS 5
#endif

#define CONFIG_ETRAX_SERIAL_RX_TIMEOUT_TICKS 5

#define CONFIG_ETRAX_SHUTDOWN_BIT 12

#define CONFIG_ETRAX_SPI_CLK_PIN "pc1"

#define CONFIG_ETRAX_SPI_CS_PIN "pc3"

#define CONFIG_ETRAX_SPI_DATAIN_PIN "pc16"

#define CONFIG_ETRAX_SPI_DATAOUT_PIN "pc0"

#define CONFIG_ETRAX_SPI_MMC_CD_GPIO_PIN "pd11"

#define CONFIG_ETRAX_SPI_MMC_CD_SSER0_PIN "pd11"

#define CONFIG_ETRAX_SPI_MMC_CD_SSER1_PIN "pd12"

#define CONFIG_ETRAX_SPI_MMC_WP_GPIO_PIN "pd10"

#define CONFIG_ETRAX_SPI_MMC_WP_SSER0_PIN "pd10"

#define CONFIG_ETRAX_SPI_MMC_WP_SSER1_PIN "pd9"

//WARNING: no defaults for CONFIG_ETRAX_V32_I2C_CLK_PORT
#define CONFIG_ETRAX_V32_I2C_CLK_PORT ""

//WARNING: no defaults for CONFIG_ETRAX_V32_I2C_DATA_PORT
#define CONFIG_ETRAX_V32_I2C_DATA_PORT ""

#define CONFIG_ETRAX_V32_LED2G "PA5"

#define CONFIG_ETRAX_V32_LED2R "PA6"

#define CONFIG_ETRAX_V32_LED3G "PA7"

#define CONFIG_ETRAX_V32_LED3R "PA7"

//WARNING: no defaults for CONFIG_ETRAX_VIRTUAL_GPIO_INTERRUPT_PA_PIN
#define CONFIG_ETRAX_VIRTUAL_GPIO_INTERRUPT_PA_PIN 0

#define CONFIG_ETRAX_VMEM_SIZE 8

//WARNING: no defaults for CONFIG_EXTRA_FIRMWARE
#define CONFIG_EXTRA_FIRMWARE ""

#define CONFIG_EXTRA_FIRMWARE_DIR "firmware"

#define CONFIG_FAT_DEFAULT_CODEPAGE 437

#define CONFIG_FAT_DEFAULT_IOCHARSET "iso8859-1"

#define CONFIG_FORCE_MAX_ZONEORDER 6

#define CONFIG_FRAME_WARN 1024

#define CONFIG_HZ 100

#define CONFIG_I2C_BLACKFIN_TWI_CLK_KHZ 50

#define CONFIG_IBM_NEW_EMAC_POLL_WEIGHT 32

#define CONFIG_IBM_NEW_EMAC_RXB 128

#define CONFIG_IBM_NEW_EMAC_RX_COPY_THRESHOLD 256

#define CONFIG_IBM_NEW_EMAC_RX_SKB_HEADROOM 0

#define CONFIG_IBM_NEW_EMAC_TXB 64

#define CONFIG_IMA_MEASURE_PCR_IDX 10

#define CONFIG_INITRAMFS_ROOT_GID 0

#define CONFIG_INITRAMFS_ROOT_UID 0

#define CONFIG_INITRAMFS_SOURCE ""

#define CONFIG_INIT_ENV_ARG_LIMIT 32

#define CONFIG_INPUT_MOUSEDEV_SCREEN_X 1024

#define CONFIG_INPUT_MOUSEDEV_SCREEN_Y 768

#define CONFIG_IP_DCCP_CCID3_RTO 100

#define CONFIG_IP_VS_TAB_BITS 12

#define CONFIG_JFFS2_FS_DEBUG 0

#define CONFIG_KERNELVERSION "2.6.30-vamos"

#define CONFIG_KGDB_TESTS_BOOT_STRING "V1F100"

#define CONFIG_KMEMCHECK_QUEUE_SIZE 64

#define CONFIG_KMEMCHECK_SHADOW_COPY_SHIFT 5

#define CONFIG_LEGACY_PTY_COUNT 256

//WARNING: no defaults for CONFIG_LOCALVERSION
#define CONFIG_LOCALVERSION ""

#define CONFIG_LOG_BUF_SHIFT 17

#define CONFIG_LSM_MMAP_MIN_ADDR 65536

#undef CONFIG_MAC80211_RC_DEFAULT
#if ((defined(CONFIG_NET) && defined(CONFIG_WIRELESS) && defined(CONFIG_MAC80211) && defined(CONFIG_MAC80211_RC_DEFAULT_MINSTREL)) || (defined(CONFIG_MAC80211_RC_DEFAULT_MINSTREL) && ((defined(CONFIG_NET) && defined(CONFIG_WIRELESS) && defined(CONFIG_MAC80211)) || (defined(CONFIG_NET) && defined(CONFIG_WIRELESS) && (defined(CONFIG_MAC80211) || defined(CONFIG_MAC80211_MODULE))))))
  #define CONFIG_MAC80211_RC_DEFAULT "minstrel"
#endif
#if ((!defined(CONFIG_MAC80211_RC_DEFAULT_MINSTREL) || ((!defined(CONFIG_NET) || !defined(CONFIG_WIRELESS) || (!defined(CONFIG_MAC80211) && !defined(CONFIG_MAC80211_MODULE))) && (!defined(CONFIG_NET) || !defined(CONFIG_WIRELESS) || !defined(CONFIG_MAC80211)))) && (!defined(CONFIG_NET) || !defined(CONFIG_WIRELESS) || !defined(CONFIG_MAC80211) || !defined(CONFIG_MAC80211_RC_DEFAULT_MINSTREL)) && ((defined(CONFIG_NET) && defined(CONFIG_WIRELESS) && defined(CONFIG_MAC80211) && defined(CONFIG_MAC80211_RC_DEFAULT_PID)) || (defined(CONFIG_MAC80211_RC_DEFAULT_PID) && ((defined(CONFIG_NET) && defined(CONFIG_WIRELESS) && defined(CONFIG_MAC80211)) || (defined(CONFIG_NET) && defined(CONFIG_WIRELESS) && (defined(CONFIG_MAC80211) || defined(CONFIG_MAC80211_MODULE)))))))
  #define CONFIG_MAC80211_RC_DEFAULT "pid"
#endif
#if ((!defined(CONFIG_NET) || !defined(CONFIG_WIRELESS) || !defined(CONFIG_MAC80211) || !defined(CONFIG_MAC80211_RC_DEFAULT_MINSTREL)) && (!defined(CONFIG_NET) || !defined(CONFIG_WIRELESS) || !defined(CONFIG_MAC80211) || !defined(CONFIG_MAC80211_RC_DEFAULT_PID)) && ((defined(CONFIG_NET) && defined(CONFIG_WIRELESS) && defined(CONFIG_MAC80211)) || (defined(CONFIG_NET) && defined(CONFIG_WIRELESS) && (defined(CONFIG_MAC80211) || defined(CONFIG_MAC80211_MODULE)))) && (!defined(CONFIG_MAC80211_RC_DEFAULT_PID) || ((!defined(CONFIG_NET) || !defined(CONFIG_WIRELESS) || (!defined(CONFIG_MAC80211) && !defined(CONFIG_MAC80211_MODULE))) && (!defined(CONFIG_NET) || !defined(CONFIG_WIRELESS) || !defined(CONFIG_MAC80211)))) && (!defined(CONFIG_MAC80211_RC_DEFAULT_MINSTREL) || ((!defined(CONFIG_NET) || !defined(CONFIG_WIRELESS) || (!defined(CONFIG_MAC80211) && !defined(CONFIG_MAC80211_MODULE))) && (!defined(CONFIG_NET) || !defined(CONFIG_WIRELESS) || !defined(CONFIG_MAC80211)))))
  #define CONFIG_MAC80211_RC_DEFAULT ""
#endif

#define CONFIG_MAX_RAW_DEVS 256

#define CONFIG_MG_DISK_RES 0

#define CONFIG_MSP_FLASH_MAP_LIMIT 0x02000000

#define CONFIG_MTDRAM_ABS_POS 0

#define CONFIG_MTDRAM_ERASE_SIZE 128

#define CONFIG_MTDRAM_TOTAL_SIZE 4096

#define CONFIG_MTD_DEBUG_VERBOSE 0

#define CONFIG_MTD_DILNETPC_BOOTSIZE 0x80000

#undef CONFIG_MTD_DOCPROBE_ADDRESS
#if ((defined(CONFIG_MTD_DOCPROBE) && defined(CONFIG_MTD) && defined(CONFIG_MTD_DOCPROBE_ADVANCED)) || (defined(CONFIG_MTD_DOCPROBE_ADVANCED) && ((defined(CONFIG_MTD_DOCPROBE) && defined(CONFIG_MTD)) || ((defined(CONFIG_MTD) || defined(CONFIG_MTD_MODULE)) && (defined(CONFIG_MTD_DOCPROBE) || defined(CONFIG_MTD_DOCPROBE_MODULE))))))
  #define CONFIG_MTD_DOCPROBE_ADDRESS 0x0000
#endif
#if ((!defined(CONFIG_MTD_DOCPROBE_ADVANCED) || (((!defined(CONFIG_MTD) && !defined(CONFIG_MTD_MODULE)) || (!defined(CONFIG_MTD_DOCPROBE) && !defined(CONFIG_MTD_DOCPROBE_MODULE))) && (!defined(CONFIG_MTD_DOCPROBE) || !defined(CONFIG_MTD)))) && (!defined(CONFIG_MTD_DOCPROBE) || !defined(CONFIG_MTD) || !defined(CONFIG_MTD_DOCPROBE_ADVANCED)) && ((defined(CONFIG_MTD_DOCPROBE) && defined(CONFIG_MTD) && !defined(CONFIG_MTD_DOCPROBE_ADVANCED)) || (!defined(CONFIG_MTD_DOCPROBE_ADVANCED) && ((defined(CONFIG_MTD_DOCPROBE) && defined(CONFIG_MTD)) || ((defined(CONFIG_MTD) || defined(CONFIG_MTD_MODULE)) && (defined(CONFIG_MTD_DOCPROBE) || defined(CONFIG_MTD_DOCPROBE_MODULE)))))))
  #define CONFIG_MTD_DOCPROBE_ADDRESS 0
#endif

#define CONFIG_MTD_NAND_DISKONCHIP_PROBE_ADDRESS 0

#define CONFIG_MTD_PHYSMAP_BANKWIDTH 2

#define CONFIG_MTD_PHYSMAP_LEN 0

#define CONFIG_MTD_PHYSMAP_START 0x8000000

#define CONFIG_MTD_REDBOOT_DIRECTORY_BLOCK -1

#define CONFIG_MTD_UBI_BEB_RESERVE 1

#define CONFIG_MTD_UBI_WL_THRESHOLD 4096

#define CONFIG_NET_EMATCH_STACK 32

#define CONFIG_NLS_DEFAULT "iso8859-1"

#define CONFIG_NOMMU_INITIAL_TRIM_EXCESS 1

//WARNING: no defaults for CONFIG_NR_QUICK
#define CONFIG_NR_QUICK 0

#define CONFIG_PANEL_BOOT_MESSAGE ""

#define CONFIG_PANEL_KEYPAD 0

#define CONFIG_PANEL_LCD 0

#define CONFIG_PANEL_LCD_BWIDTH 40

#define CONFIG_PANEL_LCD_CHARSET 0

#define CONFIG_PANEL_LCD_HEIGHT 2

#define CONFIG_PANEL_LCD_HWIDTH 64

#define CONFIG_PANEL_LCD_PIN_BL 0

#define CONFIG_PANEL_LCD_PIN_E 14

#define CONFIG_PANEL_LCD_PIN_RS 17

#define CONFIG_PANEL_LCD_PIN_RW 16

#define CONFIG_PANEL_LCD_PIN_SCL 1

#define CONFIG_PANEL_LCD_PIN_SDA 2

#define CONFIG_PANEL_LCD_PROTO 0

#define CONFIG_PANEL_LCD_WIDTH 40

#define CONFIG_PANEL_PARPORT 0

#define CONFIG_PANEL_PROFILE 5

#define CONFIG_RCU_FANOUT 32

#define CONFIG_RIONET_RX_SIZE 128

#define CONFIG_RIONET_TX_SIZE 128

#define CONFIG_RTC_DRV_AT91SAM9_GPBR 0

#define CONFIG_RTC_DRV_AT91SAM9_RTT 0

#define CONFIG_RTC_HCTOSYS_DEVICE "rtc0"

#define CONFIG_SCx200_I2C_SCL 12

#define CONFIG_SCx200_I2C_SDA 13

#define CONFIG_SECURITY_SELINUX_BOOTPARAM_VALUE 1

#define CONFIG_SECURITY_SELINUX_CHECKREQPROT_VALUE 1

#define CONFIG_SECURITY_SELINUX_POLICYDB_VERSION_MAX_VALUE 19

#define CONFIG_SERIAL_8250_NR_UARTS 4

#define CONFIG_SERIAL_8250_RUNTIME_UARTS 4

#define CONFIG_SERIAL_MCF_BAUDRATE 19200

#define CONFIG_SERIAL_MPC52xx_CONSOLE_BAUD 9600

//WARNING: no defaults for CONFIG_SERIAL_SAMSUNG_UARTS
#define CONFIG_SERIAL_SAMSUNG_UARTS 0

#define CONFIG_SERIAL_SH_SCI_NR_UARTS 2

#define CONFIG_SERIAL_TXX9_NR_UARTS 6

#define CONFIG_SMB_NLS_REMOTE "cp437"

#undef CONFIG_SPLIT_PTLOCK_CPUS
#if (defined(CONFIG_DEBUG_SPINLOCK) || defined(CONFIG_DEBUG_LOCK_ALLOC))
  #define CONFIG_SPLIT_PTLOCK_CPUS 999999
#endif
#if (!defined(CONFIG_DEBUG_SPINLOCK) && !defined(CONFIG_DEBUG_LOCK_ALLOC))
  #define CONFIG_SPLIT_PTLOCK_CPUS 4
#endif

#undef CONFIG_SPORT_BAUD_RATE
#if ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT) && defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200)) || (defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200) && ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT)) || (defined(CONFIG_HAS_IOMEM) && (defined(CONFIG_SERIAL_BFIN_SPORT) || defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))))))
  #define CONFIG_SPORT_BAUD_RATE 115200
#endif
#if ((!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200)) && ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT) && defined(CONFIG_SERIAL_SPORT_BAUD_RATE_57600)) || (defined(CONFIG_SERIAL_SPORT_BAUD_RATE_57600) && ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT)) || (defined(CONFIG_HAS_IOMEM) && (defined(CONFIG_SERIAL_BFIN_SPORT) || defined(CONFIG_SERIAL_BFIN_SPORT_MODULE)))))))
  #define CONFIG_SPORT_BAUD_RATE 57600
#endif
#if ((!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_57600) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_57600)) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200)) && ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT) && defined(CONFIG_SERIAL_SPORT_BAUD_RATE_38400)) || (defined(CONFIG_SERIAL_SPORT_BAUD_RATE_38400) && ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT)) || (defined(CONFIG_HAS_IOMEM) && (defined(CONFIG_SERIAL_BFIN_SPORT) || defined(CONFIG_SERIAL_BFIN_SPORT_MODULE)))))) && (!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))))
  #define CONFIG_SPORT_BAUD_RATE 38400
#endif
#if ((!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_38400) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))) && (!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_57600) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_57600)) && ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT) && defined(CONFIG_SERIAL_SPORT_BAUD_RATE_19200)) || (defined(CONFIG_SERIAL_SPORT_BAUD_RATE_19200) && ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT)) || (defined(CONFIG_HAS_IOMEM) && (defined(CONFIG_SERIAL_BFIN_SPORT) || defined(CONFIG_SERIAL_BFIN_SPORT_MODULE)))))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200)) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_38400)) && (!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))))
  #define CONFIG_SPORT_BAUD_RATE 19200
#endif
#if ((!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_38400) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))) && (!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_57600) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_57600)) && ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT) && defined(CONFIG_SERIAL_SPORT_BAUD_RATE_9600)) || (defined(CONFIG_SERIAL_SPORT_BAUD_RATE_9600) && ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT)) || (defined(CONFIG_HAS_IOMEM) && (defined(CONFIG_SERIAL_BFIN_SPORT) || defined(CONFIG_SERIAL_BFIN_SPORT_MODULE)))))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_19200)) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200)) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_38400)) && (!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))) && (!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_19200) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))))
  #define CONFIG_SPORT_BAUD_RATE 9600
#endif

#define CONFIG_SQUASHFS_FRAGMENT_CACHE_SIZE 3

#define CONFIG_TIPC_CLUSTERS 1

#define CONFIG_TIPC_LOG 0

#define CONFIG_TIPC_NODES 255

#define CONFIG_TIPC_PORTS 8191

#define CONFIG_TIPC_SLAVE_NODES 0

#define CONFIG_TIPC_ZONES 3

#define CONFIG_UART0_CTS_PIN 23

#define CONFIG_UART0_RTS_PIN 22

#define CONFIG_UART1_CTS_PIN -1

#define CONFIG_UART1_RTS_PIN -1

#define CONFIG_UART2_CTS_PIN -1

#define CONFIG_UART2_RTS_PIN -1

#define CONFIG_UART3_CTS_PIN -1

#define CONFIG_UART3_RTS_PIN -1

#define CONFIG_UBIFS_FS_DEBUG_MSG_LVL 0

#define CONFIG_UEVENT_HELPER_PATH "/sbin/hotplug"

#define CONFIG_USB_GADGET_VBUS_DRAW 2

#define CONFIG_WIMAX_DEBUG_LEVEL 8

#define CONFIG_WIMAX_I2400M_DEBUG_LEVEL 8

#undef CONFIG_ZONE_DMA_FLAG
#if !defined(CONFIG_ZONE_DMA)
  #define CONFIG_ZONE_DMA_FLAG 0
#endif
#if defined(CONFIG_ZONE_DMA)
  #define CONFIG_ZONE_DMA_FLAG 1
#endif

