#define CONFIG_ARCH "h8300"

#define CONFIG_ATM_FORE200E_DEBUG 0

#define CONFIG_ATM_FORE200E_TX_RETRY 16

#undef CONFIG_BASE_SMALL
#if defined(CONFIG_BASE_FULL)
  #define CONFIG_BASE_SMALL 0
#endif
#if !defined(CONFIG_BASE_FULL)
  #define CONFIG_BASE_SMALL 1
#endif

#define CONFIG_BFIN_RX_DESC_NUM 20

#define CONFIG_BFIN_TX_DESC_NUM 10

//WARNING: no defaults for CONFIG_BLKDEV_RESERVE_ADDRESS
#define CONFIG_BLKDEV_RESERVE_ADDRESS 0

#define CONFIG_BLK_DEV_RAM_COUNT 16

#define CONFIG_BLK_DEV_RAM_SIZE 4096

#undef CONFIG_BOOTPARAM_HUNG_TASK_PANIC_VALUE
#if (defined(CONFIG_DETECT_HUNG_TASK) && !defined(CONFIG_BOOTPARAM_HUNG_TASK_PANIC))
  #define CONFIG_BOOTPARAM_HUNG_TASK_PANIC_VALUE 0
#endif
#if (defined(CONFIG_DETECT_HUNG_TASK) && defined(CONFIG_BOOTPARAM_HUNG_TASK_PANIC) && (!defined(CONFIG_DETECT_HUNG_TASK) || defined(CONFIG_BOOTPARAM_HUNG_TASK_PANIC)))
  #define CONFIG_BOOTPARAM_HUNG_TASK_PANIC_VALUE 1
#endif

#undef CONFIG_BOOTPARAM_SOFTLOCKUP_PANIC_VALUE
#if (defined(CONFIG_DETECT_SOFTLOCKUP) && !defined(CONFIG_BOOTPARAM_SOFTLOCKUP_PANIC))
  #define CONFIG_BOOTPARAM_SOFTLOCKUP_PANIC_VALUE 0
#endif
#if (defined(CONFIG_DETECT_SOFTLOCKUP) && defined(CONFIG_BOOTPARAM_SOFTLOCKUP_PANIC) && (!defined(CONFIG_DETECT_SOFTLOCKUP) || defined(CONFIG_BOOTPARAM_SOFTLOCKUP_PANIC)))
  #define CONFIG_BOOTPARAM_SOFTLOCKUP_PANIC_VALUE 1
#endif

#define CONFIG_CDROM_PKTCDVD_BUFFERS 8

#define CONFIG_CPU_CLOCK 20000

#define CONFIG_DE2104X_DSL 0

#define CONFIG_DEBUG_KMEMLEAK_EARLY_LOG_SIZE 400

#define CONFIG_DEBUG_OBJECTS_ENABLE_DEFAULT 1

#undef CONFIG_DEFAULT_IOSCHED
#if (defined(CONFIG_BLOCK) && defined(CONFIG_DEFAULT_DEADLINE))
  #define CONFIG_DEFAULT_IOSCHED "deadline"
#endif
#if (defined(CONFIG_BLOCK) && defined(CONFIG_DEFAULT_CFQ) && (!defined(CONFIG_BLOCK) || !defined(CONFIG_DEFAULT_DEADLINE)))
  #define CONFIG_DEFAULT_IOSCHED "cfq"
#endif
#if (defined(CONFIG_BLOCK) && defined(CONFIG_DEFAULT_NOOP) && (!defined(CONFIG_BLOCK) || !defined(CONFIG_DEFAULT_CFQ)) && (!defined(CONFIG_BLOCK) || !defined(CONFIG_DEFAULT_DEADLINE)))
  #define CONFIG_DEFAULT_IOSCHED "noop"
#endif

#define CONFIG_DEFAULT_MMAP_MIN_ADDR 4096

#undef CONFIG_DEFAULT_SECURITY
#if defined(CONFIG_DEFAULT_SECURITY_SELINUX)
  #define CONFIG_DEFAULT_SECURITY "selinux"
#endif
#if (defined(CONFIG_DEFAULT_SECURITY_SMACK) && !defined(CONFIG_DEFAULT_SECURITY_SELINUX))
  #define CONFIG_DEFAULT_SECURITY "smack"
#endif
#if (!defined(CONFIG_DEFAULT_SECURITY_SELINUX) && !defined(CONFIG_DEFAULT_SECURITY_SMACK) && defined(CONFIG_DEFAULT_SECURITY_TOMOYO))
  #define CONFIG_DEFAULT_SECURITY "tomoyo"
#endif
#if (!defined(CONFIG_DEFAULT_SECURITY_SELINUX) && !defined(CONFIG_DEFAULT_SECURITY_SMACK) && !defined(CONFIG_DEFAULT_SECURITY_TOMOYO) && defined(CONFIG_DEFAULT_SECURITY_DAC))
  #define CONFIG_DEFAULT_SECURITY ""
#endif

#undef CONFIG_DEFAULT_TCP_CONG
#if (defined(CONFIG_NET) && defined(CONFIG_DEFAULT_WESTWOOD) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_VEGAS)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_BIC)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_HTCP)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_CUBIC)) && defined(CONFIG_INET))
  #define CONFIG_DEFAULT_TCP_CONG "westwood"
#endif
#if (defined(CONFIG_NET) && defined(CONFIG_DEFAULT_HTCP) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_BIC)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_CUBIC)) && defined(CONFIG_INET))
  #define CONFIG_DEFAULT_TCP_CONG "htcp"
#endif
#if (defined(CONFIG_NET) && defined(CONFIG_INET) && defined(CONFIG_DEFAULT_BIC))
  #define CONFIG_DEFAULT_TCP_CONG "bic"
#endif
#if ((defined(CONFIG_NET) && defined(CONFIG_INET) && defined(CONFIG_DEFAULT_CUBIC) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_BIC))) || (defined(CONFIG_NET) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_RENO)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_VEGAS)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_BIC)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_HTCP)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_WESTWOOD)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_CUBIC)) && defined(CONFIG_INET)))
  #define CONFIG_DEFAULT_TCP_CONG "cubic"
#endif
#if (defined(CONFIG_DEFAULT_RENO) && defined(CONFIG_NET) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_VEGAS)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_BIC)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_HTCP)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_WESTWOOD)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_CUBIC)) && defined(CONFIG_INET))
  #define CONFIG_DEFAULT_TCP_CONG "reno"
#endif
#if (defined(CONFIG_NET) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_BIC)) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_HTCP)) && defined(CONFIG_DEFAULT_VEGAS) && (!defined(CONFIG_NET) || !defined(CONFIG_INET) || !defined(CONFIG_DEFAULT_CUBIC)) && defined(CONFIG_INET))
  #define CONFIG_DEFAULT_TCP_CONG "vegas"
#endif

#define CONFIG_DEFCONFIG_LIST "/lib/modules/$UNAME_RELEASE/.config"

#define CONFIG_DLCI_MAX 8

#define CONFIG_DM9000_DEBUGLEVEL 4

//WARNING: no defaults for CONFIG_EXTRA_FIRMWARE
#define CONFIG_EXTRA_FIRMWARE ""

#define CONFIG_EXTRA_FIRMWARE_DIR "firmware"

#define CONFIG_FAT_DEFAULT_CODEPAGE 437

#define CONFIG_FAT_DEFAULT_IOCHARSET "iso8859-1"

#define CONFIG_FRAME_WARN 1024

#undef CONFIG_H8300_IDE_ALT
#if ((defined(CONFIG_H8300H_AKI3068NET) && defined(CONFIG_IDE)) || (defined(CONFIG_H8300H_AKI3068NET) && (defined(CONFIG_IDE) || defined(CONFIG_IDE_MODULE))) || (((defined(CONFIG_H8300H_AKI3068NET) && defined(CONFIG_IDE)) || (defined(CONFIG_H8300H_AKI3068NET) && (defined(CONFIG_IDE) || defined(CONFIG_IDE_MODULE)))) && (!defined(CONFIG_H8300H_H8MAX) || (!defined(CONFIG_IDE) && !defined(CONFIG_IDE_MODULE))) && (!defined(CONFIG_H8300H_AKI3068NET) || (!defined(CONFIG_IDE) && !defined(CONFIG_IDE_MODULE))) && (!defined(CONFIG_H8300H_AKI3068NET) || !defined(CONFIG_IDE)) && (!defined(CONFIG_H8300H_H8MAX) || !defined(CONFIG_IDE))))
  #define CONFIG_H8300_IDE_ALT 0
#endif
#if (((!defined(CONFIG_H8300H_AKI3068NET) || (!defined(CONFIG_IDE) && !defined(CONFIG_IDE_MODULE))) && (!defined(CONFIG_H8300H_AKI3068NET) || !defined(CONFIG_IDE)) && ((defined(CONFIG_H8300H_H8MAX) && defined(CONFIG_IDE)) || (defined(CONFIG_H8300H_H8MAX) && (defined(CONFIG_IDE) || defined(CONFIG_IDE_MODULE))))) || (((defined(CONFIG_H8300H_H8MAX) && defined(CONFIG_IDE)) || (defined(CONFIG_H8300H_H8MAX) && (defined(CONFIG_IDE) || defined(CONFIG_IDE_MODULE)))) && (!defined(CONFIG_H8300H_H8MAX) || (!defined(CONFIG_IDE) && !defined(CONFIG_IDE_MODULE))) && (!defined(CONFIG_H8300H_AKI3068NET) || (!defined(CONFIG_IDE) && !defined(CONFIG_IDE_MODULE))) && (!defined(CONFIG_H8300H_AKI3068NET) || !defined(CONFIG_IDE)) && (!defined(CONFIG_H8300H_H8MAX) || !defined(CONFIG_IDE))))
  #define CONFIG_H8300_IDE_ALT 0x60000c
#endif

#undef CONFIG_H8300_IDE_BASE
#if ((defined(CONFIG_H8300H_AKI3068NET) && defined(CONFIG_IDE)) || (defined(CONFIG_H8300H_AKI3068NET) && (defined(CONFIG_IDE) || defined(CONFIG_IDE_MODULE))) || (((defined(CONFIG_H8300H_AKI3068NET) && defined(CONFIG_IDE)) || (defined(CONFIG_H8300H_AKI3068NET) && (defined(CONFIG_IDE) || defined(CONFIG_IDE_MODULE)))) && (!defined(CONFIG_H8300H_H8MAX) || (!defined(CONFIG_IDE) && !defined(CONFIG_IDE_MODULE))) && (!defined(CONFIG_H8300H_AKI3068NET) || (!defined(CONFIG_IDE) && !defined(CONFIG_IDE_MODULE))) && (!defined(CONFIG_H8300H_AKI3068NET) || !defined(CONFIG_IDE)) && (!defined(CONFIG_H8300H_H8MAX) || !defined(CONFIG_IDE))))
  #define CONFIG_H8300_IDE_BASE 0
#endif
#if (((!defined(CONFIG_H8300H_AKI3068NET) || (!defined(CONFIG_IDE) && !defined(CONFIG_IDE_MODULE))) && (!defined(CONFIG_H8300H_AKI3068NET) || !defined(CONFIG_IDE)) && ((defined(CONFIG_H8300H_H8MAX) && defined(CONFIG_IDE)) || (defined(CONFIG_H8300H_H8MAX) && (defined(CONFIG_IDE) || defined(CONFIG_IDE_MODULE))))) || (((defined(CONFIG_H8300H_H8MAX) && defined(CONFIG_IDE)) || (defined(CONFIG_H8300H_H8MAX) && (defined(CONFIG_IDE) || defined(CONFIG_IDE_MODULE)))) && (!defined(CONFIG_H8300H_H8MAX) || (!defined(CONFIG_IDE) && !defined(CONFIG_IDE_MODULE))) && (!defined(CONFIG_H8300H_AKI3068NET) || (!defined(CONFIG_IDE) && !defined(CONFIG_IDE_MODULE))) && (!defined(CONFIG_H8300H_AKI3068NET) || !defined(CONFIG_IDE)) && (!defined(CONFIG_H8300H_H8MAX) || !defined(CONFIG_IDE))))
  #define CONFIG_H8300_IDE_BASE 0x200000
#endif

#undef CONFIG_H8300_IDE_IRQ
#if ((defined(CONFIG_H8300H_AKI3068NET) && defined(CONFIG_IDE)) || (defined(CONFIG_H8300H_AKI3068NET) && (defined(CONFIG_IDE) || defined(CONFIG_IDE_MODULE))) || (((defined(CONFIG_H8300H_AKI3068NET) && defined(CONFIG_IDE)) || (defined(CONFIG_H8300H_AKI3068NET) && (defined(CONFIG_IDE) || defined(CONFIG_IDE_MODULE)))) && (!defined(CONFIG_H8300H_H8MAX) || (!defined(CONFIG_IDE) && !defined(CONFIG_IDE_MODULE))) && (!defined(CONFIG_H8300H_AKI3068NET) || (!defined(CONFIG_IDE) && !defined(CONFIG_IDE_MODULE))) && (!defined(CONFIG_H8300H_AKI3068NET) || !defined(CONFIG_IDE)) && (!defined(CONFIG_H8300H_H8MAX) || !defined(CONFIG_IDE))))
  #define CONFIG_H8300_IDE_IRQ 0
#endif
#if (((!defined(CONFIG_H8300H_AKI3068NET) || (!defined(CONFIG_IDE) && !defined(CONFIG_IDE_MODULE))) && (!defined(CONFIG_H8300H_AKI3068NET) || !defined(CONFIG_IDE)) && ((defined(CONFIG_H8300H_H8MAX) && defined(CONFIG_IDE)) || (defined(CONFIG_H8300H_H8MAX) && (defined(CONFIG_IDE) || defined(CONFIG_IDE_MODULE))))) || (((defined(CONFIG_H8300H_H8MAX) && defined(CONFIG_IDE)) || (defined(CONFIG_H8300H_H8MAX) && (defined(CONFIG_IDE) || defined(CONFIG_IDE_MODULE)))) && (!defined(CONFIG_H8300H_H8MAX) || (!defined(CONFIG_IDE) && !defined(CONFIG_IDE_MODULE))) && (!defined(CONFIG_H8300H_AKI3068NET) || (!defined(CONFIG_IDE) && !defined(CONFIG_IDE_MODULE))) && (!defined(CONFIG_H8300H_AKI3068NET) || !defined(CONFIG_IDE)) && (!defined(CONFIG_H8300H_H8MAX) || !defined(CONFIG_IDE))))
  #define CONFIG_H8300_IDE_IRQ 5
#endif

//WARNING: no defaults for CONFIG_H8300_ITU_CH
#define CONFIG_H8300_ITU_CH 0

//WARNING: no defaults for CONFIG_H8300_TIMER16_CH
#define CONFIG_H8300_TIMER16_CH 0

//WARNING: no defaults for CONFIG_H8300_TPU_CH
#define CONFIG_H8300_TPU_CH 0

#define CONFIG_HZ 100

#define CONFIG_I2C_BLACKFIN_TWI_CLK_KHZ 50

#define CONFIG_IBM_NEW_EMAC_POLL_WEIGHT 32

#define CONFIG_IBM_NEW_EMAC_RXB 128

#define CONFIG_IBM_NEW_EMAC_RX_COPY_THRESHOLD 256

#define CONFIG_IBM_NEW_EMAC_RX_SKB_HEADROOM 0

#define CONFIG_IBM_NEW_EMAC_TXB 64

#define CONFIG_IMA_MEASURE_PCR_IDX 10

#define CONFIG_INITRAMFS_ROOT_GID 0

#define CONFIG_INITRAMFS_ROOT_UID 0

#define CONFIG_INITRAMFS_SOURCE ""

#define CONFIG_INIT_ENV_ARG_LIMIT 32

#define CONFIG_INPUT_MOUSEDEV_SCREEN_X 1024

#define CONFIG_INPUT_MOUSEDEV_SCREEN_Y 768

#define CONFIG_IP_DCCP_CCID3_RTO 100

#define CONFIG_IP_VS_TAB_BITS 12

#define CONFIG_JFFS2_FS_DEBUG 0

#define CONFIG_KERNELVERSION "2.6.30-vamos"

//WARNING: no defaults for CONFIG_KERNEL_COMMAND
#define CONFIG_KERNEL_COMMAND ""

#define CONFIG_KGDB_TESTS_BOOT_STRING "V1F100"

#define CONFIG_KMEMCHECK_QUEUE_SIZE 64

#define CONFIG_KMEMCHECK_SHADOW_COPY_SHIFT 5

//WARNING: no defaults for CONFIG_LOCALVERSION
#define CONFIG_LOCALVERSION ""

#define CONFIG_LOG_BUF_SHIFT 17

#define CONFIG_LSM_MMAP_MIN_ADDR 65536

#undef CONFIG_MAC80211_RC_DEFAULT
#if ((defined(CONFIG_NET) && defined(CONFIG_WIRELESS) && defined(CONFIG_MAC80211) && defined(CONFIG_MAC80211_RC_DEFAULT_MINSTREL)) || (defined(CONFIG_MAC80211_RC_DEFAULT_MINSTREL) && ((defined(CONFIG_NET) && defined(CONFIG_WIRELESS) && defined(CONFIG_MAC80211)) || (defined(CONFIG_NET) && defined(CONFIG_WIRELESS) && (defined(CONFIG_MAC80211) || defined(CONFIG_MAC80211_MODULE))))))
  #define CONFIG_MAC80211_RC_DEFAULT "minstrel"
#endif
#if ((!defined(CONFIG_MAC80211_RC_DEFAULT_MINSTREL) || ((!defined(CONFIG_NET) || !defined(CONFIG_WIRELESS) || (!defined(CONFIG_MAC80211) && !defined(CONFIG_MAC80211_MODULE))) && (!defined(CONFIG_NET) || !defined(CONFIG_WIRELESS) || !defined(CONFIG_MAC80211)))) && (!defined(CONFIG_NET) || !defined(CONFIG_WIRELESS) || !defined(CONFIG_MAC80211) || !defined(CONFIG_MAC80211_RC_DEFAULT_MINSTREL)) && ((defined(CONFIG_NET) && defined(CONFIG_WIRELESS) && defined(CONFIG_MAC80211) && defined(CONFIG_MAC80211_RC_DEFAULT_PID)) || (defined(CONFIG_MAC80211_RC_DEFAULT_PID) && ((defined(CONFIG_NET) && defined(CONFIG_WIRELESS) && defined(CONFIG_MAC80211)) || (defined(CONFIG_NET) && defined(CONFIG_WIRELESS) && (defined(CONFIG_MAC80211) || defined(CONFIG_MAC80211_MODULE)))))))
  #define CONFIG_MAC80211_RC_DEFAULT "pid"
#endif
#if ((!defined(CONFIG_NET) || !defined(CONFIG_WIRELESS) || !defined(CONFIG_MAC80211) || !defined(CONFIG_MAC80211_RC_DEFAULT_MINSTREL)) && (!defined(CONFIG_NET) || !defined(CONFIG_WIRELESS) || !defined(CONFIG_MAC80211) || !defined(CONFIG_MAC80211_RC_DEFAULT_PID)) && ((defined(CONFIG_NET) && defined(CONFIG_WIRELESS) && defined(CONFIG_MAC80211)) || (defined(CONFIG_NET) && defined(CONFIG_WIRELESS) && (defined(CONFIG_MAC80211) || defined(CONFIG_MAC80211_MODULE)))) && (!defined(CONFIG_MAC80211_RC_DEFAULT_PID) || ((!defined(CONFIG_NET) || !defined(CONFIG_WIRELESS) || (!defined(CONFIG_MAC80211) && !defined(CONFIG_MAC80211_MODULE))) && (!defined(CONFIG_NET) || !defined(CONFIG_WIRELESS) || !defined(CONFIG_MAC80211)))) && (!defined(CONFIG_MAC80211_RC_DEFAULT_MINSTREL) || ((!defined(CONFIG_NET) || !defined(CONFIG_WIRELESS) || (!defined(CONFIG_MAC80211) && !defined(CONFIG_MAC80211_MODULE))) && (!defined(CONFIG_NET) || !defined(CONFIG_WIRELESS) || !defined(CONFIG_MAC80211)))))
  #define CONFIG_MAC80211_RC_DEFAULT ""
#endif

#define CONFIG_MG_DISK_RES 0

#define CONFIG_MSP_FLASH_MAP_LIMIT 0x02000000

#define CONFIG_MTDRAM_ABS_POS 0

#define CONFIG_MTDRAM_ERASE_SIZE 128

#define CONFIG_MTDRAM_TOTAL_SIZE 4096

#define CONFIG_MTD_DEBUG_VERBOSE 0

#define CONFIG_MTD_DILNETPC_BOOTSIZE 0x80000

#undef CONFIG_MTD_DOCPROBE_ADDRESS
#if ((defined(CONFIG_MTD) && defined(CONFIG_MTD_DOCPROBE) && defined(CONFIG_MTD_DOCPROBE_ADVANCED)) || (defined(CONFIG_MTD_DOCPROBE_ADVANCED) && ((defined(CONFIG_MTD) && defined(CONFIG_MTD_DOCPROBE)) || ((defined(CONFIG_MTD_DOCPROBE) || defined(CONFIG_MTD_DOCPROBE_MODULE)) && (defined(CONFIG_MTD) || defined(CONFIG_MTD_MODULE))))))
  #define CONFIG_MTD_DOCPROBE_ADDRESS 0x0000
#endif
#if ((!defined(CONFIG_MTD_DOCPROBE_ADVANCED) || (((!defined(CONFIG_MTD_DOCPROBE) && !defined(CONFIG_MTD_DOCPROBE_MODULE)) || (!defined(CONFIG_MTD) && !defined(CONFIG_MTD_MODULE))) && (!defined(CONFIG_MTD) || !defined(CONFIG_MTD_DOCPROBE)))) && (!defined(CONFIG_MTD) || !defined(CONFIG_MTD_DOCPROBE) || !defined(CONFIG_MTD_DOCPROBE_ADVANCED)) && ((defined(CONFIG_MTD) && defined(CONFIG_MTD_DOCPROBE) && !defined(CONFIG_MTD_DOCPROBE_ADVANCED)) || (!defined(CONFIG_MTD_DOCPROBE_ADVANCED) && ((defined(CONFIG_MTD) && defined(CONFIG_MTD_DOCPROBE)) || ((defined(CONFIG_MTD_DOCPROBE) || defined(CONFIG_MTD_DOCPROBE_MODULE)) && (defined(CONFIG_MTD) || defined(CONFIG_MTD_MODULE)))))))
  #define CONFIG_MTD_DOCPROBE_ADDRESS 0
#endif

#define CONFIG_MTD_NAND_DISKONCHIP_PROBE_ADDRESS 0

#define CONFIG_MTD_PHYSMAP_BANKWIDTH 2

#define CONFIG_MTD_PHYSMAP_LEN 0

#define CONFIG_MTD_PHYSMAP_START 0x8000000

#define CONFIG_MTD_REDBOOT_DIRECTORY_BLOCK -1

#define CONFIG_MTD_UBI_BEB_RESERVE 1

#define CONFIG_MTD_UBI_WL_THRESHOLD 4096

#define CONFIG_NET_EMATCH_STACK 32

#define CONFIG_NLS_DEFAULT "iso8859-1"

#define CONFIG_NOMMU_INITIAL_TRIM_EXCESS 1

//WARNING: no defaults for CONFIG_NR_QUICK
#define CONFIG_NR_QUICK 0

#define CONFIG_PANEL_BOOT_MESSAGE ""

#define CONFIG_PANEL_KEYPAD 0

#define CONFIG_PANEL_LCD 0

#define CONFIG_PANEL_LCD_BWIDTH 40

#define CONFIG_PANEL_LCD_CHARSET 0

#define CONFIG_PANEL_LCD_HEIGHT 2

#define CONFIG_PANEL_LCD_HWIDTH 64

#define CONFIG_PANEL_LCD_PIN_BL 0

#define CONFIG_PANEL_LCD_PIN_E 14

#define CONFIG_PANEL_LCD_PIN_RS 17

#define CONFIG_PANEL_LCD_PIN_RW 16

#define CONFIG_PANEL_LCD_PIN_SCL 1

#define CONFIG_PANEL_LCD_PIN_SDA 2

#define CONFIG_PANEL_LCD_PROTO 0

#define CONFIG_PANEL_LCD_WIDTH 40

#define CONFIG_PANEL_PARPORT 0

#define CONFIG_PANEL_PROFILE 5

#define CONFIG_RCU_FANOUT 32

#define CONFIG_RIONET_RX_SIZE 128

#define CONFIG_RIONET_TX_SIZE 128

#define CONFIG_SCx200_I2C_SCL 12

#define CONFIG_SCx200_I2C_SDA 13

#define CONFIG_SECURITY_SELINUX_BOOTPARAM_VALUE 1

#define CONFIG_SECURITY_SELINUX_CHECKREQPROT_VALUE 1

#define CONFIG_SECURITY_SELINUX_POLICYDB_VERSION_MAX_VALUE 19

#define CONFIG_SERIAL_8250_NR_UARTS 4

#define CONFIG_SERIAL_8250_RUNTIME_UARTS 4

#define CONFIG_SERIAL_MCF_BAUDRATE 19200

#define CONFIG_SERIAL_MPC52xx_CONSOLE_BAUD 9600

//WARNING: no defaults for CONFIG_SERIAL_SAMSUNG_UARTS
#define CONFIG_SERIAL_SAMSUNG_UARTS 0

#define CONFIG_SERIAL_SH_SCI_NR_UARTS 2

#define CONFIG_SERIAL_TXX9_NR_UARTS 6

#define CONFIG_SMB_NLS_REMOTE "cp437"

#undef CONFIG_SPLIT_PTLOCK_CPUS
#if (defined(CONFIG_DEBUG_SPINLOCK) || defined(CONFIG_DEBUG_LOCK_ALLOC))
  #define CONFIG_SPLIT_PTLOCK_CPUS 999999
#endif
#if (!defined(CONFIG_DEBUG_SPINLOCK) && !defined(CONFIG_DEBUG_LOCK_ALLOC))
  #define CONFIG_SPLIT_PTLOCK_CPUS 4
#endif

#undef CONFIG_SPORT_BAUD_RATE
#if ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT) && defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200)) || (defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200) && ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT)) || (defined(CONFIG_HAS_IOMEM) && (defined(CONFIG_SERIAL_BFIN_SPORT) || defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))))))
  #define CONFIG_SPORT_BAUD_RATE 115200
#endif
#if ((!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200)) && ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT) && defined(CONFIG_SERIAL_SPORT_BAUD_RATE_57600)) || (defined(CONFIG_SERIAL_SPORT_BAUD_RATE_57600) && ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT)) || (defined(CONFIG_HAS_IOMEM) && (defined(CONFIG_SERIAL_BFIN_SPORT) || defined(CONFIG_SERIAL_BFIN_SPORT_MODULE)))))))
  #define CONFIG_SPORT_BAUD_RATE 57600
#endif
#if ((!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_57600) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_57600)) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200)) && ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT) && defined(CONFIG_SERIAL_SPORT_BAUD_RATE_38400)) || (defined(CONFIG_SERIAL_SPORT_BAUD_RATE_38400) && ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT)) || (defined(CONFIG_HAS_IOMEM) && (defined(CONFIG_SERIAL_BFIN_SPORT) || defined(CONFIG_SERIAL_BFIN_SPORT_MODULE)))))) && (!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))))
  #define CONFIG_SPORT_BAUD_RATE 38400
#endif
#if ((!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_38400) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))) && (!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_57600) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_57600)) && ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT) && defined(CONFIG_SERIAL_SPORT_BAUD_RATE_19200)) || (defined(CONFIG_SERIAL_SPORT_BAUD_RATE_19200) && ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT)) || (defined(CONFIG_HAS_IOMEM) && (defined(CONFIG_SERIAL_BFIN_SPORT) || defined(CONFIG_SERIAL_BFIN_SPORT_MODULE)))))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200)) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_38400)) && (!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))))
  #define CONFIG_SPORT_BAUD_RATE 19200
#endif
#if ((!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_38400) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))) && (!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_57600) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_57600)) && ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT) && defined(CONFIG_SERIAL_SPORT_BAUD_RATE_9600)) || (defined(CONFIG_SERIAL_SPORT_BAUD_RATE_9600) && ((defined(CONFIG_HAS_IOMEM) && defined(CONFIG_SERIAL_BFIN_SPORT)) || (defined(CONFIG_HAS_IOMEM) && (defined(CONFIG_SERIAL_BFIN_SPORT) || defined(CONFIG_SERIAL_BFIN_SPORT_MODULE)))))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_19200)) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200)) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT) || !defined(CONFIG_SERIAL_SPORT_BAUD_RATE_38400)) && (!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_115200) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))) && (!defined(CONFIG_SERIAL_SPORT_BAUD_RATE_19200) || ((!defined(CONFIG_HAS_IOMEM) || (!defined(CONFIG_SERIAL_BFIN_SPORT) && !defined(CONFIG_SERIAL_BFIN_SPORT_MODULE))) && (!defined(CONFIG_HAS_IOMEM) || !defined(CONFIG_SERIAL_BFIN_SPORT)))))
  #define CONFIG_SPORT_BAUD_RATE 9600
#endif

#define CONFIG_SQUASHFS_FRAGMENT_CACHE_SIZE 3

#define CONFIG_SYMBOL_PREFIX "_"

#define CONFIG_TIPC_CLUSTERS 1

#define CONFIG_TIPC_LOG 0

#define CONFIG_TIPC_NODES 255

#define CONFIG_TIPC_PORTS 8191

#define CONFIG_TIPC_SLAVE_NODES 0

#define CONFIG_TIPC_ZONES 3

#define CONFIG_UART0_CTS_PIN 23

#define CONFIG_UART0_RTS_PIN 22

#define CONFIG_UART1_CTS_PIN -1

#define CONFIG_UART1_RTS_PIN -1

#define CONFIG_UART2_CTS_PIN -1

#define CONFIG_UART2_RTS_PIN -1

#define CONFIG_UART3_CTS_PIN -1

#define CONFIG_UART3_RTS_PIN -1

#define CONFIG_UBIFS_FS_DEBUG_MSG_LVL 0

#define CONFIG_UEVENT_HELPER_PATH "/sbin/hotplug"

#define CONFIG_USB_GADGET_VBUS_DRAW 2

#define CONFIG_WIMAX_DEBUG_LEVEL 8

#define CONFIG_WIMAX_I2400M_DEBUG_LEVEL 8

#undef CONFIG_ZONE_DMA_FLAG
#if !defined(CONFIG_ZONE_DMA)
  #define CONFIG_ZONE_DMA_FLAG 0
#endif
#if defined(CONFIG_ZONE_DMA)
  #define CONFIG_ZONE_DMA_FLAG 1
#endif

